### ISSUE TITLE
Deploy Automan on Polygon, Base, OP, Avax, BNB.

### ISSUE THREAD

**Issue by gaohan137** [Aperture-Finance/uniswap-v3-automan#16]

**Comment by gnarlycow** [comment]
Gnosis-safe addresses: https://www.notion.so/aperture-finance/b96af03e0a01426083a4677fa7c1af84?v=123ab0d756584f289b3a405a8c2be1bc&pvs=4

Funded Polygon deployer with 1 MATIC: https://polygonscan.com/tx/0x9db857bf975d6b85b3ead947ff1cf402deff5709932d35be1ccc49790d4beaa4

**Comment by gnarlycow** [comment]
https://bscscan.com/tx/0x6d351f2ef4d1171429acbb43f6e95eb87d00e475b989526667d680d4aa38dda9

**Comment by gnarlycow** [comment]
The gnosis-safe addresses for all 8 chains are now also available on OZ Defender dashboard at https://defender.openzeppelin.com/#/admin

**Comment by gnarlycow** [comment]
Removed Celo from the scope of this deployment because code changes are required to work with the absence of WETH9 on Celo.  Let's defer Celo deployment for now.  Details: https://github.com/Aperture-Finance/uniswap-v3-automation-helpers/blob/7d6e76e2049c1464873616890be20039fe59b5d2/chain.ts#L230
