### ISSUE TITLE
`invariantZeroBalance` failure

### ISSUE THREAD

**Issue by gnarlycow** [Aperture-Finance/uniswap-v3-automan#38]
I encountered the following error when running tests:

> Failing tests:
> Encountered 1 failing test in test/UniV3Automan.t.sol:UniV3AutomanTest
> [FAIL. Reason: failed to set up invariant testing environment: [targetSelectors] address does not have an associated contract: 0x2e234DAe75C793f67A35089C9d99245E1C58470b] invariantZeroBalance() (runs: 0, calls: 0, reverts: 0)

All other tests are passing.  @shuhuiluo Any thoughts on what the issue might be?

**Comment by shuhuiluo** [comment]
It's a Foundry issue.
Run
```Shell
forge clean
forge build
forge test
```

**Comment by gnarlycow** [comment]
Thanks, Shuhui! That worked. I will update README with that information.
